language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: api-rest-share-idea-nodejs
  api_key:
    secure: tg5Y4a1lgdjv/6ORTzBAscZdxCNL9Wmr/xF8PuW6kuTecX3B/m1CPqs9iI0IiU/jFvbYyGp06swLILjcrKcQpPlXDsVBIxRPswkpLxEAEJYksnwgdP6O3KVViUi2OGuAqSIHNyX6m6Nf9nG9+7BOwHs6OamhlTgKB00VR2CvOMHWLpAR4n+3OWYRilzPXKF08g79nlAKDLtk2koL1p/OEzs5QGY/MZAfkY0nIsTnJz7g3IbLRf+/rHlfJtqXt6c/u2iAc36BOWH1FTd8SW68u+Aunkp36uX2VK/V/RYacHPbJYEtnLwl8SIhMlcxN4Sgy9nqzowtZLDLuZxrl5r/5au6FTsoZWe9nIhFzwMAAbG73KSW+H5Z0IGL6Tg3YfuwtCesnH4/EpF7bhw7eLNVxXSqlBpV7OoXIiH9DgrSdqKEQEMbNRICFcUS0OtF64JcAmlr3oQUrv3giga3zfYvMEyrC8C2QYBaiYmaqYp78w17LJVtcoL9fqRQDOe+1DQzE9YHmVua59ApRf5bnWoWYObtPIic64Sj1NU4P5DASRDYwan6cPvChy6m7BThcY+QPhGafApQ/pSMsSGgBQ23Huq32DzPbd5Z401qtYNQTAmRUoRvoGKi9V3zeUgIq4bQc/n3igv07HDooKHFoYFA0vwEzuNWkjz8IUfPPo9YyKw=
