language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: api-rest-share-idea-nodejs
  api_key:
    secure: oc70SYyLuunQNnl8pNc5ieVOWTqPRJwHd/IoVDv1GVcQb2/YM4wCSPFP1xwC2HcMnuiySEcb2Nx/v9UJyYslbDMvcUQ6e6NUSR5eNFKfnDxV8Is3UOqZxWAkOjJ4G1G/B/q5fvElM3gweMPzb7tzTsNU5H4autF2YEAiKIzcuXqazUzmcGyrRtKjAKAscvRRMLpEwxk0XduGe3EV/FARJqtFu4fM5JBwk1Nf2n0bnTxTuGtbbVFwSrh+QTDsOgBUmS+7KDrMWvxv4gy3j6UHURYzVx2d1VVnhZsR7gw2BRwWxlacGOk4ZkJj25ywQJ2/QXl+ZR81iv1FcYfCkeQj04oPvfRTB8Q+e8vUCcPxA2wYpiKoWEXZIZtfQ5UmLtgtVhPMyLvYagjGGwn4dgL9H+JOJwY0a25RNbId1kN8w31boafI+z5z1J/nY1oW6mnZ6YW0fbiHTvDAHcD/JjqBbX+ipHwu4cD0Qf05eAUr8hIcQpa6V+/Ay4cqIefT9GTK0LhvTfe8dFrkY656/bov1gY0Bck8ILFy56S16e2x6N7mE1SYsKlhvFzP5S6NevG6C4gjHZjgm1F3AXis51maqwwFifeHUyMRShJkR9kS9U7CqmytVXTeR/jy8ggYjRtz0fL1ChkNgDs3PvnxR+vpTWfbX9d5hcHEzfnG6h74JoU=
